
apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-todo-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-todo
  template:
    metadata:
      labels:
        app: react-todo
    spec:
      containers:
      - name: react-todo-container
        image: prudhvi1247/react:latest  # Replace with your Docker image
        ports:
        - containerPort: 3000  # Assuming your React app listens on port 80
